name: Build and Publish Pod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: false
        type: string
        default: "New release"

env:
  FRAMEWORK_NAME: "MyAwesomeKit"
  XCODE_VERSION: "15.0"

jobs:
  build-and-publish:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v3

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Build XCFramework
        run: |
          chmod +x ./scripts/build_framework.sh
          ./scripts/build_framework.sh ${{ env.FRAMEWORK_NAME }}

      - name: Create Git Tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Authenticate with Github Packages
        run: |
          echo "source 'https://rubygems.org'" > ~/.gemrc
          bundle config --global ACCESS_PACKAGES_TOKEN ${{ secrets.ACCESS_TOKEN }}

      - name: Publish to Github Packages
        run: |
          pod repo push ACCESS-packages MyAwesomeKit.podspec --allow-warnings
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: ${{ inputs.release_notes }}
          files: |
            output/${{ env.FRAMEWORK_NAME }}.xcframework
            ${{ env.FRAMEWORK_NAME }}.podspec
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
