name: Build and Publish Pod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.0.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: false
        type: string
        default: "New release"

env:
  FRAMEWORK_NAME: "MyAwesomeKit"
  DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer

jobs:
  build-and-publish:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch ${DEVELOPER_DIR}

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/build_framework.sh
          chmod +x ./scripts/validate_pod.sh

      - name: Build XCFramework
        run: ./scripts/build_framework.sh ${{ env.FRAMEWORK_NAME }}

      - name: Create Git Tag
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Validate and Push Pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          ./scripts/validate_pod.sh ${{ env.FRAMEWORK_NAME }} true ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: ${{ inputs.release_notes }}
          files: |
            output/${{ env.FRAMEWORK_NAME }}.xcframework
            ${{ env.FRAMEWORK_NAME }}.podspec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
